apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-ha.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "mongodb-ha.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "mongodb-ha.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb